from diff_cov.coverage_parser import CoverageParser
from diff_cov.diff_parser import DiffParser
import argparse
import subprocess
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("diff_branch", help="diff branch/commit to compare against")
    parser.add_argument("curr_branch", help="current branch/commit to compare")
    parser.add_argument("-cf", "--coverage_file", help="coverage file generated by running 'coverage json'", default="coverage.json", required=False)
    args = parser.parse_args()
    output = subprocess.run(["git", "diff", "--unified=0", args.diff_branch, args.curr_branch], capture_output=True)
    data = output.stdout.decode("utf-8")
    print(data)
    diff_parser = DiffParser(data)
    diff_parser.parse()
    coverage_parser = CoverageParser(args.coverage_file, diff_parser)
    coverage_parser.parse()
